### ISSUE TITLE
useEffect fire only in Browser environment

### ISSUE THREAD

**Issue by efleurine** [dejorrit/scroll-data-hook#4]
`useEffect` only runs in the browser so this check is not really needed

https://github.com/dejorrit/scroll-data-hook/blob/9010dd5032c7de6c7859d73471e9ac9a399e3e5f/src/index.tsx#L212

Your code helped me, thanks

**Comment by dejorrit** [comment]
@efleurine Thanks! It's removed in 1.0.4

Good to hear my code helped you :)
