### ISSUE TITLE
npm package is missing files in dist/ except index.js

### ISSUE THREAD

**Issue by tronstoner** [dejorrit/scroll-data-hook#7]
When installing the package from npm the package is missing type definitions and module builds other than index.js.
To reproduce:
```
$ yarn add scroll-data-hook
$ ls node_modules/scroll-data-hook/dist/
index.js
```
Strangely enough, when building from source all files are properly packaged in the tarball.

I am planning on using this lib with a big client and would be grateful if this could be fixed.

**Comment by dejorrit** [comment]
@tronstoner Thanks for opening the issue. I updated the package.json file to be more specific on what files need to be in the tarball before publishing to npm. 

Can you upgrade to 1.0.2 and let me know if everything works?

Thanks!

**Comment by tronstoner** [comment]
@dejorrit Thanks, it now looks like all files are included, yet there still seems to be something broken:
```
import { useScrollData } from "scroll-data-hook"
```

Will result in the following TS error:
```
Module '"../../../../../node_modules/scroll-data-hook/dist/types"' has no exported member 'useScrollData'. ts(2305)
```

It seems to work when I change package.json like this:
```
  "types": "dist/index.d.ts",
```

Thanks!

**Comment by dejorrit** [comment]
@tronstoner Thanks for checking. I just pushed a new patch fixing this.

Please let me know if it works now. Thanks!

**Comment by tronstoner** [comment]
@dejorrit Thanks for you quick response, got no errors anymore.
